package namegen

// Adjectives copied verbatim from /server/src/utils/nameGenerator.js (line 3-29).
var Adjectives = []string{
	"Cosmic", "Stellar", "Lunar", "Solar", "Arctic", "Mystic", "Silent", "Swift",
	"Noble", "Brave", "Calm", "Gentle", "Vivid", "Bright", "Wild", "Bold",
	"Clever", "Fierce", "Golden", "Hidden", "Iron", "Jade", "Kind", "Lucky",
	"Mighty", "Nimble", "Proud", "Quick", "Royal", "Sharp", "Tough", "Warm",
	"Ancient", "Binary", "Crystal", "Dark", "Electric", "Frozen", "Grand", "Hollow",
	"Inner", "Jet", "Keen", "Lone", "Mellow", "Neon", "Outer", "Pale",
	"Quantum", "Rapid", "Smooth", "Tidal", "Ultra", "Vast", "Wired", "Zen",
	"Amber", "Blue", "Coral", "Dusk", "Ember", "Flint", "Gray", "Haze",
	"Ivory", "Jasper", "Krypton", "Lava", "Marble", "Night", "Onyx", "Pearl",
	"Quartz", "Rust", "Sage", "Thorn", "Umbra", "Void", "Wisp", "Zinc",
	"Astral", "Blaze", "Chrome", "Drift", "Echo", "Forge", "Ghost", "Hyper",
	"Infra", "Jolt", "Karma", "Lush", "Mist", "Nova", "Orbit", "Pixel",
	"Quiet", "Ridge", "Storm", "Terra", "Urban", "Venom", "Wave", "Xeno",
	"Apex", "Bloom", "Cipher", "Dawn", "Ether", "Frost", "Glow", "Haven",
	"Isle", "Jewel", "Knot", "Lyric", "Moss", "Nebula", "Opal", "Prism",
	"Rune", "Shard", "Tide", "Umber", "Veil", "Woven", "Zenith", "Aero",
	"Brisk", "Crisp", "Deep", "Ebon", "Feral", "Granite", "Halo", "Indigo",
	"Jubilant", "Keen", "Lithic", "Muted", "Nimbus", "Obsidian", "Polar", "Quill",
	"Radiant", "Serene", "Turbo", "Verdant", "Wistful", "Xylem", "Yielding", "Zephyr",
	"Argent", "Basalt", "Cobalt", "Dusky", "Emerald", "Floral", "Glacial", "Helix",
	"Iridescent", "Jasmine", "Kelp", "Lucid", "Magma", "Nectar", "Ochre", "Phosphor",
	"Quasar", "Ripple", "Scarlet", "Topaz", "Umbral", "Velvet", "Warp", "Xeric",
	"Yonder", "Zircon", "Alpine", "Burnt", "Cedar", "Dew", "Elm", "Fern",
	"Grove", "Heath", "Ivy", "Juniper", "Kin", "Lichen", "Maple", "Nettle",
	"Oak", "Pine", "Quince", "Reed", "Spruce", "Thistle", "Ursine", "Violet",
}

// Nouns copied verbatim from /server/src/utils/nameGenerator.js (line 31-57).
var Nouns = []string{
	"Penguin", "Falcon", "Wolf", "Tiger", "Eagle", "Raven", "Fox", "Bear",
	"Hawk", "Lynx", "Otter", "Panda", "Crane", "Cobra", "Dove", "Elk",
	"Gecko", "Heron", "Ibis", "Jaguar", "Koala", "Lion", "Moose", "Newt",
	"Owl", "Pike", "Robin", "Shark", "Trout", "Viper", "Whale", "Yak",
	"Atlas", "Beacon", "Comet", "Delta", "Enigma", "Flare", "Glyph", "Helix",
	"Index", "Joker", "Karma", "Laser", "Matrix", "Nexus", "Omega", "Pulse",
	"Quest", "Relay", "Signal", "Token", "Unity", "Vector", "Warden", "Zenith",
	"Anchor", "Blade", "Crown", "Dagger", "Edge", "Forge", "Guard", "Helm",
	"Iris", "Jewel", "Knight", "Lance", "Mace", "Nomad", "Oracle", "Phantom",
	"Quiver", "Ranger", "Scout", "Titan", "Usher", "Vortex", "Wraith", "Exile",
	"Arrow", "Bolt", "Cipher", "Drift", "Ember", "Frost", "Glider", "Hunter",
	"Icon", "Judge", "Keeper", "Lancer", "Monk", "Ninja", "Outlaw", "Pilot",
	"Quasar", "Rider", "Sage", "Tempest", "Ultima", "Vigil", "Walker", "Xerus",
	"Aegis", "Baron", "Crest", "Drake", "Envoy", "Fang", "Grail", "Harbinger",
	"Imp", "Jackal", "Kite", "Locus", "Myth", "Node", "Omen", "Prism",
	"Relic", "Sentry", "Torch", "Ursa", "Valor", "Wisp", "Zeal", "Bastion",
	"Circuit", "Dynamo", "Flux", "Grid", "Hive", "Jinx", "Kernel", "Link",
	"Module", "Nave", "Optic", "Portal", "Quill", "Rover", "Spire", "Turret",
	"Vertex", "Watcher", "Axis", "Bridge", "Core", "Dome", "Frame", "Gate",
	"Hub", "Key", "Loop", "Mesh", "Orbit", "Path", "Rift", "Shell",
	"Trace", "Vault", "Web", "Zone", "Apex", "Byte", "Cog", "Disk",
	"Echo", "File", "Gist", "Hash", "Ink", "Jar", "Knob", "Log",
	"Map", "Net", "Orb", "Pin", "Ring", "Seed", "Tag", "Urn",
	"Vine", "Wing", "Yew", "Zap", "Blitz", "Charm", "Dune", "Flint",
	"Gleam", "Horn", "Isle", "Jade", "Knoll", "Ledge", "Mound", "Notch",
}
